# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ipAddress', models.TextField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set([('latitude', 'longitude')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
